### ISSUE TITLE
Questions about the type of this flatpak wallet

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.groestlcoin.groestlcoin-qt#1]
Hi dear.
I visit your official site & founded 3 type of desktop official wallet for your cryptocurrency:
https://www.groestlcoin.org/downloads/

- Groestlcoin Core
- Electrum-GRS
- GRSD

So, which of these 3 is this flatpak package ? It seem to be "Groestlcoin Core", isn't it ? I need your replay to be sure from that .....

If this flatpak is "Groestlcoin Core", then:

1) why name differ here ?

2) can you, kindly, add "ElectrumGRS" light wallet to FlatHub as flatpak ? Many users do not like to download full blockchain .......

**Comment by gruve-p** [comment]
Hello,

This flatpak package is groestlcoin-qt which is part of Groestlcoin Core. 
Groestlcoin Core is a full suite that that comes bundled with:
groestlcoin-qt (Groestlcoin Core GUI)
groestlcoind (Groestlcoin Core daemon)
groestlcoin-cli (Groestlcoin Core RPC client)
groestlcoin-tx (Groestlcoin Core transaction utility)
groestlcoin-wallet (Groestlcoin Core wallet tool)

1. This flatpack should indicate the it is the gui, so should contain (or equal) qt or gui. Otherwise it can be confused with the daemon.

2. We can certainly try. Is this request coming from you as a groestlcoin user?

**Comment by Nokia808** [comment]
@gruve-p 
1) so is this flatpak package contain all those (GUI + daemon + ......) as all in one, or only GUI & when user set it, it will download the remainder of package from external source outside FlatHub ?

2) I'm not a groestlcoin user, & in-fact I hear about it for 1st time when I saw your PR for this package ....

**Comment by gruve-p** [comment]
1. This flatpak package only contains the GUI so only groestlcoin-qt hence the name similar as https://flathub.org/apps/details/org.bitcoincore.bitcoin-qt

2. I will submit a PR in future to include Electrum-GRS

**Comment by Nokia808** [comment]
@gruve-p 
Okay I understood. However, I have the following suggestion: I suggest on you to add a note, to appear in GNOME software, saying "it is full node official wallet of groestlcoin" or something like this.

Please do not delay PR for light wallet Electrum-GRS ..... Most users are just buy & sale small amount of coins for bought goods online & prefer light wallets ....

Regarding Electron-GRS, I would like to bring your attention to the fact that "Electrum Bitcoin wallet" already existing as flatpak in FlatHub - see:
https://github.com/flathub/org.electrum.electrum

Please see it's pull request that already merged:
flathub/flathub#1102

The above link will help you too much when you package Electrum-GRS as flatpak for FlatHub. It will assist you to abbreviate the way by avoiding you from mistakes that already done during original packaging PR - see:
flathub/flathub#837

Thank you.

**Comment by gruve-p** [comment]
https://github.com/flathub/org.groestlcoin.electrum-grs

**Comment by Nokia808** [comment]
Yes, I saw it. Thank you very much ! You assist FlatHub by making electrum-grs available in it as flatpak! Moreover, your step will make other cryptocurrencies make the same in near future. This way, FlatHub/flatpak elevated to sky by make it easier for Linuxers to use cryptocurrencies & enjoying their revolution ....
